import { chromium } from 'playwright';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
const base = process.env.PLAYWRIGHT_BROWSERS_PATH;
const exe = readdirSync(base).filter(n=>n.startsWith('chromium-')).map(n=>join(base,n,'chrome-linux','chrome')).find(existsSync);
const browser = await chromium.launch({ executablePath: exe });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = [];
page.on('pageerror', e => errors.push(String(e)));
page.on('console', m => { if (m.type()==='error' && !m.text().includes('404')) errors.push(m.text()); });
await page.goto('http://127.0.0.1:8080/docs/index.html', { waitUntil: 'load' });
await page.waitForFunction(() => !!window.__api);
console.log('menu caché au départ :', await page.isHidden('#menu'));

await page.fill('[data-doc="titre"]', 'Remplacer un toner sur MFP Sharp');
await page.fill('[data-doc="sousTitre"]', 'Identification de la référence, remplacement et traçabilité.');
await page.fill('[data-doc="objectif"]', 'Remplacer un toner vide et tracer l’intervention dans le BI.');
await page.fill('[data-doc="prerequis"]', 'BI ouvert dans CopyPark ; toner de remplacement en stock technicien.');
await page.fill('[data-doc="resultat"]', 'Le toner est remplacé et le BI est clôturé.');
await page.screenshot({ path: 'output/wiz1.png' });

await page.click('#btn-next');
await page.waitForSelector('[data-role="shot"]');
const b64 = readFileSync('content/assets/datec/etape-01.png').toString('base64');
await page.evaluate((b64) => {
  const bin = atob(b64); const arr = new Uint8Array(bin.length);
  for (let i=0;i<bin.length;i++) arr[i]=bin.charCodeAt(i);
  const dt = new DataTransfer(); dt.items.add(new File([arr], 'c.png', { type:'image/png' }));
  document.dispatchEvent(new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true }));
}, b64);
await page.waitForFunction(() => document.querySelector('#status')?.textContent.includes('Capture ajoutée'));
console.log('invite de collage cachée après ajout :', await page.isHidden('[data-role="shot-empty"]'));
await page.fill('[data-step="titre"]', 'Relever la référence du toner');
await page.fill('[data-step="action"]', 'Ouvrir le BI dans CopyPark et relever le modèle de la machine, puis la référence exacte du toner correspondant à la couleur épuisée.');
await page.fill('[data-step="resultat"]', 'La référence du toner à commander est identifiée.');
await page.click('[data-action="add-callout"]');
await page.fill('.extra [data-field="label"]', 'POINT D’ARRÊT OBLIGATOIRE');
await page.fill('.extra [data-field="texte"]', 'Ne pas jeter la cartouche usagée avant d’avoir relevé sa référence.');
await page.waitForTimeout(300);
await page.screenshot({ path: 'output/wiz2.png', fullPage: true });

await page.click('#btn-next');
await page.fill('[data-step="titre"]', 'Remplacer le toner et sortir le stock');
await page.fill('[data-step="action"]', 'Remplacer la cartouche, puis saisir la sortie de stock technicien dans le BI.');
await page.fill('[data-step="resultat"]', 'Le toner est remplacé et sorti du stock du technicien.');
await page.click('#btn-next');
await page.waitForSelector('[data-action="suggest"]');
await page.click('[data-action="suggest"]');
await page.waitForTimeout(300);
await page.screenshot({ path: 'output/wiz3.png' });
await page.click('[data-action="preview"]');
await page.waitForSelector('#overlay:not([hidden])', { timeout: 60000 });
await page.waitForTimeout(3000);
await page.screenshot({ path: 'output/wiz4.png' });
console.log('erreurs console :', errors.length ? errors : 'AUCUNE');
await browser.close();
